-- CreateTable
CREATE TABLE IF NOT EXISTS `citrus_intake` (
    `id` VARCHAR(30) NOT NULL,
    `supplier` VARCHAR(255) NOT NULL,
    `vehicle_plate` VARCHAR(50) NULL,
    `date` VARCHAR(20) NULL,
    `truck_number` VARCHAR(100) NOT NULL,
    `container_number` VARCHAR(100) NULL,
    `seal_number` VARCHAR(100) NULL,
    `oranges_class1` INT NOT NULL DEFAULT 0,
    `oranges_class2` INT NOT NULL DEFAULT 0,
    `oranges_class3` INT NOT NULL DEFAULT 0,
    `oranges_total_boxes` INT NOT NULL DEFAULT 0,
    `oranges_total_weight` DOUBLE NOT NULL DEFAULT 0,
    `lemons_class1` INT NOT NULL DEFAULT 0,
    `lemons_class2` INT NOT NULL DEFAULT 0,
    `lemons_class3` INT NOT NULL DEFAULT 0,
    `lemons_total_boxes` INT NOT NULL DEFAULT 0,
    `lemons_total_weight` DOUBLE NOT NULL DEFAULT 0,
    `tangerines_class1` INT NOT NULL DEFAULT 0,
    `tangerines_class2` INT NOT NULL DEFAULT 0,
    `tangerines_class3` INT NOT NULL DEFAULT 0,
    `tangerines_total_boxes` INT NOT NULL DEFAULT 0,
    `tangerines_total_weight` DOUBLE NOT NULL DEFAULT 0,
    `grand_total_boxes` INT NOT NULL DEFAULT 0,
    `grand_total_weight` DOUBLE NOT NULL DEFAULT 0,
    `notes` TEXT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),

    INDEX `citrus_intake_supplier_idx`(`supplier`),
    INDEX `citrus_intake_truck_number_idx`(`truck_number`),
    INDEX `citrus_intake_created_at_idx`(`created_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
